#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logica
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hospitales")]
	public partial class OrmHospitalesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcalificacion(calificacion instance);
    partial void Updatecalificacion(calificacion instance);
    partial void Deletecalificacion(calificacion instance);
    partial void Insertcentro_medico(centro_medico instance);
    partial void Updatecentro_medico(centro_medico instance);
    partial void Deletecentro_medico(centro_medico instance);
    partial void Insertcentromedico_has_especialidad(centromedico_has_especialidad instance);
    partial void Updatecentromedico_has_especialidad(centromedico_has_especialidad instance);
    partial void Deletecentromedico_has_especialidad(centromedico_has_especialidad instance);
    partial void Insertcita_medica(cita_medica instance);
    partial void Updatecita_medica(cita_medica instance);
    partial void Deletecita_medica(cita_medica instance);
    partial void Insertconsulta(consulta instance);
    partial void Updateconsulta(consulta instance);
    partial void Deleteconsulta(consulta instance);
    partial void Inserteps(eps instance);
    partial void Updateeps(eps instance);
    partial void Deleteeps(eps instance);
    partial void Inserteps_has_centromedico(eps_has_centromedico instance);
    partial void Updateeps_has_centromedico(eps_has_centromedico instance);
    partial void Deleteeps_has_centromedico(eps_has_centromedico instance);
    partial void Insertespecialidad(especialidad instance);
    partial void Updateespecialidad(especialidad instance);
    partial void Deleteespecialidad(especialidad instance);
    partial void Inserttelefono(telefono instance);
    partial void Updatetelefono(telefono instance);
    partial void Deletetelefono(telefono instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public OrmHospitalesDataContext() : 
				base(global::Logica.Properties.Settings.Default.hospitalesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrmHospitalesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmHospitalesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmHospitalesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrmHospitalesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<calificacion> calificacion
		{
			get
			{
				return this.GetTable<calificacion>();
			}
		}
		
		public System.Data.Linq.Table<centro_medico> centro_medico
		{
			get
			{
				return this.GetTable<centro_medico>();
			}
		}
		
		public System.Data.Linq.Table<centromedico_has_especialidad> centromedico_has_especialidad
		{
			get
			{
				return this.GetTable<centromedico_has_especialidad>();
			}
		}
		
		public System.Data.Linq.Table<cita_medica> cita_medica
		{
			get
			{
				return this.GetTable<cita_medica>();
			}
		}
		
		public System.Data.Linq.Table<consulta> consulta
		{
			get
			{
				return this.GetTable<consulta>();
			}
		}
		
		public System.Data.Linq.Table<eps> eps
		{
			get
			{
				return this.GetTable<eps>();
			}
		}
		
		public System.Data.Linq.Table<eps_has_centromedico> eps_has_centromedico
		{
			get
			{
				return this.GetTable<eps_has_centromedico>();
			}
		}
		
		public System.Data.Linq.Table<especialidad> especialidad
		{
			get
			{
				return this.GetTable<especialidad>();
			}
		}
		
		public System.Data.Linq.Table<telefono> telefono
		{
			get
			{
				return this.GetTable<telefono>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_consultar_cuantos_usuarios_consulta")]
		public ISingleResult<sp_consultar_cuantos_usuarios_consultaResult> sp_consultar_cuantos_usuarios_consulta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaFinal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaInicial, fechaFinal);
			return ((ISingleResult<sp_consultar_cuantos_usuarios_consultaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string nombre_usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre_usuario, contrasena);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_grafico_torta")]
		public ISingleResult<sp_grafico_tortaResult> sp_grafico_torta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> centro_medico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), centro_medico);
			return ((ISingleResult<sp_grafico_tortaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calificacion")]
	public partial class calificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_calificacion;
		
		private int _calificacion1;
		
		private string _observacion;
		
		private EntitySet<cita_medica> _cita_medica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_calificacionChanging(int value);
    partial void Onid_calificacionChanged();
    partial void Oncalificacion1Changing(int value);
    partial void Oncalificacion1Changed();
    partial void OnobservacionChanging(string value);
    partial void OnobservacionChanged();
    #endregion
		
		public calificacion()
		{
			this._cita_medica = new EntitySet<cita_medica>(new Action<cita_medica>(this.attach_cita_medica), new Action<cita_medica>(this.detach_cita_medica));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_calificacion
		{
			get
			{
				return this._id_calificacion;
			}
			set
			{
				if ((this._id_calificacion != value))
				{
					this.Onid_calificacionChanging(value);
					this.SendPropertyChanging();
					this._id_calificacion = value;
					this.SendPropertyChanged("id_calificacion");
					this.Onid_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="calificacion", Storage="_calificacion1", DbType="Int NOT NULL")]
		public int calificacion1
		{
			get
			{
				return this._calificacion1;
			}
			set
			{
				if ((this._calificacion1 != value))
				{
					this.Oncalificacion1Changing(value);
					this.SendPropertyChanging();
					this._calificacion1 = value;
					this.SendPropertyChanged("calificacion1");
					this.Oncalificacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="VarChar(MAX)")]
		public string observacion
		{
			get
			{
				return this._observacion;
			}
			set
			{
				if ((this._observacion != value))
				{
					this.OnobservacionChanging(value);
					this.SendPropertyChanging();
					this._observacion = value;
					this.SendPropertyChanged("observacion");
					this.OnobservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="calificacion_cita_medica", Storage="_cita_medica", ThisKey="id_calificacion", OtherKey="id_calificacion")]
		public EntitySet<cita_medica> cita_medica
		{
			get
			{
				return this._cita_medica;
			}
			set
			{
				this._cita_medica.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.calificacion = this;
		}
		
		private void detach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.calificacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.centro_medico")]
	public partial class centro_medico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_centro_medico;
		
		private string _nombre_centro_medico;
		
		private string _nivel_atencion;
		
		private string _horarios;
		
		private string _direccion;
		
		private string _foto;
		
		private EntitySet<centromedico_has_especialidad> _centromedico_has_especialidad;
		
		private EntitySet<cita_medica> _cita_medica;
		
		private EntitySet<consulta> _consulta;
		
		private EntitySet<eps_has_centromedico> _eps_has_centromedico;
		
		private EntitySet<telefono> _telefono;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_centro_medicoChanging(int value);
    partial void Onid_centro_medicoChanged();
    partial void Onnombre_centro_medicoChanging(string value);
    partial void Onnombre_centro_medicoChanged();
    partial void Onnivel_atencionChanging(string value);
    partial void Onnivel_atencionChanged();
    partial void OnhorariosChanging(string value);
    partial void OnhorariosChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnfotoChanging(string value);
    partial void OnfotoChanged();
    #endregion
		
		public centro_medico()
		{
			this._centromedico_has_especialidad = new EntitySet<centromedico_has_especialidad>(new Action<centromedico_has_especialidad>(this.attach_centromedico_has_especialidad), new Action<centromedico_has_especialidad>(this.detach_centromedico_has_especialidad));
			this._cita_medica = new EntitySet<cita_medica>(new Action<cita_medica>(this.attach_cita_medica), new Action<cita_medica>(this.detach_cita_medica));
			this._consulta = new EntitySet<consulta>(new Action<consulta>(this.attach_consulta), new Action<consulta>(this.detach_consulta));
			this._eps_has_centromedico = new EntitySet<eps_has_centromedico>(new Action<eps_has_centromedico>(this.attach_eps_has_centromedico), new Action<eps_has_centromedico>(this.detach_eps_has_centromedico));
			this._telefono = new EntitySet<telefono>(new Action<telefono>(this.attach_telefono), new Action<telefono>(this.detach_telefono));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_centro_medico", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_centro_medico
		{
			get
			{
				return this._id_centro_medico;
			}
			set
			{
				if ((this._id_centro_medico != value))
				{
					this.Onid_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._id_centro_medico = value;
					this.SendPropertyChanged("id_centro_medico");
					this.Onid_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_centro_medico", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_centro_medico
		{
			get
			{
				return this._nombre_centro_medico;
			}
			set
			{
				if ((this._nombre_centro_medico != value))
				{
					this.Onnombre_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._nombre_centro_medico = value;
					this.SendPropertyChanged("nombre_centro_medico");
					this.Onnombre_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel_atencion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nivel_atencion
		{
			get
			{
				return this._nivel_atencion;
			}
			set
			{
				if ((this._nivel_atencion != value))
				{
					this.Onnivel_atencionChanging(value);
					this.SendPropertyChanging();
					this._nivel_atencion = value;
					this.SendPropertyChanged("nivel_atencion");
					this.Onnivel_atencionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horarios", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string horarios
		{
			get
			{
				return this._horarios;
			}
			set
			{
				if ((this._horarios != value))
				{
					this.OnhorariosChanging(value);
					this.SendPropertyChanging();
					this._horarios = value;
					this.SendPropertyChanged("horarios");
					this.OnhorariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_centromedico_has_especialidad", Storage="_centromedico_has_especialidad", ThisKey="id_centro_medico", OtherKey="id_centro_medico")]
		public EntitySet<centromedico_has_especialidad> centromedico_has_especialidad
		{
			get
			{
				return this._centromedico_has_especialidad;
			}
			set
			{
				this._centromedico_has_especialidad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_cita_medica", Storage="_cita_medica", ThisKey="id_centro_medico", OtherKey="id_centro_medico")]
		public EntitySet<cita_medica> cita_medica
		{
			get
			{
				return this._cita_medica;
			}
			set
			{
				this._cita_medica.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_consulta", Storage="_consulta", ThisKey="id_centro_medico", OtherKey="centro_medico_id")]
		public EntitySet<consulta> consulta
		{
			get
			{
				return this._consulta;
			}
			set
			{
				this._consulta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_eps_has_centromedico", Storage="_eps_has_centromedico", ThisKey="id_centro_medico", OtherKey="id_centro_medico")]
		public EntitySet<eps_has_centromedico> eps_has_centromedico
		{
			get
			{
				return this._eps_has_centromedico;
			}
			set
			{
				this._eps_has_centromedico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_telefono", Storage="_telefono", ThisKey="id_centro_medico", OtherKey="id_centro_medico")]
		public EntitySet<telefono> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_centromedico_has_especialidad(centromedico_has_especialidad entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = this;
		}
		
		private void detach_centromedico_has_especialidad(centromedico_has_especialidad entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = null;
		}
		
		private void attach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = this;
		}
		
		private void detach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = null;
		}
		
		private void attach_consulta(consulta entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = this;
		}
		
		private void detach_consulta(consulta entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = null;
		}
		
		private void attach_eps_has_centromedico(eps_has_centromedico entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = this;
		}
		
		private void detach_eps_has_centromedico(eps_has_centromedico entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = null;
		}
		
		private void attach_telefono(telefono entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = this;
		}
		
		private void detach_telefono(telefono entity)
		{
			this.SendPropertyChanging();
			entity.centro_medico = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.centromedico_has_especialidad")]
	public partial class centromedico_has_especialidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_centro_medico;
		
		private int _id_especialidad;
		
		private EntityRef<centro_medico> _centro_medico;
		
		private EntityRef<especialidad> _especialidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_centro_medicoChanging(int value);
    partial void Onid_centro_medicoChanged();
    partial void Onid_especialidadChanging(int value);
    partial void Onid_especialidadChanged();
    #endregion
		
		public centromedico_has_especialidad()
		{
			this._centro_medico = default(EntityRef<centro_medico>);
			this._especialidad = default(EntityRef<especialidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_centro_medico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_centro_medico
		{
			get
			{
				return this._id_centro_medico;
			}
			set
			{
				if ((this._id_centro_medico != value))
				{
					if (this._centro_medico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._id_centro_medico = value;
					this.SendPropertyChanged("id_centro_medico");
					this.Onid_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialidad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_especialidad
		{
			get
			{
				return this._id_especialidad;
			}
			set
			{
				if ((this._id_especialidad != value))
				{
					if (this._especialidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_especialidadChanging(value);
					this.SendPropertyChanging();
					this._id_especialidad = value;
					this.SendPropertyChanged("id_especialidad");
					this.Onid_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_centromedico_has_especialidad", Storage="_centro_medico", ThisKey="id_centro_medico", OtherKey="id_centro_medico", IsForeignKey=true)]
		public centro_medico centro_medico
		{
			get
			{
				return this._centro_medico.Entity;
			}
			set
			{
				centro_medico previousValue = this._centro_medico.Entity;
				if (((previousValue != value) 
							|| (this._centro_medico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._centro_medico.Entity = null;
						previousValue.centromedico_has_especialidad.Remove(this);
					}
					this._centro_medico.Entity = value;
					if ((value != null))
					{
						value.centromedico_has_especialidad.Add(this);
						this._id_centro_medico = value.id_centro_medico;
					}
					else
					{
						this._id_centro_medico = default(int);
					}
					this.SendPropertyChanged("centro_medico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialidad_centromedico_has_especialidad", Storage="_especialidad", ThisKey="id_especialidad", OtherKey="id_especialidad", IsForeignKey=true)]
		public especialidad especialidad
		{
			get
			{
				return this._especialidad.Entity;
			}
			set
			{
				especialidad previousValue = this._especialidad.Entity;
				if (((previousValue != value) 
							|| (this._especialidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._especialidad.Entity = null;
						previousValue.centromedico_has_especialidad.Remove(this);
					}
					this._especialidad.Entity = value;
					if ((value != null))
					{
						value.centromedico_has_especialidad.Add(this);
						this._id_especialidad = value.id_especialidad;
					}
					else
					{
						this._id_especialidad = default(int);
					}
					this.SendPropertyChanged("especialidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cita_medica")]
	public partial class cita_medica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cita_medica;
		
		private System.DateTime _fecha_hora;
		
		private int _id_centro_medico;
		
		private long _usuario_cedula;
		
		private System.Nullable<int> _id_calificacion;
		
		private EntityRef<calificacion> _calificacion;
		
		private EntityRef<centro_medico> _centro_medico;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cita_medicaChanging(int value);
    partial void Onid_cita_medicaChanged();
    partial void Onfecha_horaChanging(System.DateTime value);
    partial void Onfecha_horaChanged();
    partial void Onid_centro_medicoChanging(int value);
    partial void Onid_centro_medicoChanged();
    partial void Onusuario_cedulaChanging(long value);
    partial void Onusuario_cedulaChanged();
    partial void Onid_calificacionChanging(System.Nullable<int> value);
    partial void Onid_calificacionChanged();
    #endregion
		
		public cita_medica()
		{
			this._calificacion = default(EntityRef<calificacion>);
			this._centro_medico = default(EntityRef<centro_medico>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cita_medica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cita_medica
		{
			get
			{
				return this._id_cita_medica;
			}
			set
			{
				if ((this._id_cita_medica != value))
				{
					this.Onid_cita_medicaChanging(value);
					this.SendPropertyChanging();
					this._id_cita_medica = value;
					this.SendPropertyChanged("id_cita_medica");
					this.Onid_cita_medicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_hora", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_hora
		{
			get
			{
				return this._fecha_hora;
			}
			set
			{
				if ((this._fecha_hora != value))
				{
					this.Onfecha_horaChanging(value);
					this.SendPropertyChanging();
					this._fecha_hora = value;
					this.SendPropertyChanged("fecha_hora");
					this.Onfecha_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_centro_medico", DbType="Int NOT NULL")]
		public int id_centro_medico
		{
			get
			{
				return this._id_centro_medico;
			}
			set
			{
				if ((this._id_centro_medico != value))
				{
					if (this._centro_medico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._id_centro_medico = value;
					this.SendPropertyChanged("id_centro_medico");
					this.Onid_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_cedula", DbType="BigInt NOT NULL")]
		public long usuario_cedula
		{
			get
			{
				return this._usuario_cedula;
			}
			set
			{
				if ((this._usuario_cedula != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usuario_cedula = value;
					this.SendPropertyChanged("usuario_cedula");
					this.Onusuario_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_calificacion", DbType="Int")]
		public System.Nullable<int> id_calificacion
		{
			get
			{
				return this._id_calificacion;
			}
			set
			{
				if ((this._id_calificacion != value))
				{
					if (this._calificacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_calificacionChanging(value);
					this.SendPropertyChanging();
					this._id_calificacion = value;
					this.SendPropertyChanged("id_calificacion");
					this.Onid_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="calificacion_cita_medica", Storage="_calificacion", ThisKey="id_calificacion", OtherKey="id_calificacion", IsForeignKey=true)]
		public calificacion calificacion
		{
			get
			{
				return this._calificacion.Entity;
			}
			set
			{
				calificacion previousValue = this._calificacion.Entity;
				if (((previousValue != value) 
							|| (this._calificacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._calificacion.Entity = null;
						previousValue.cita_medica.Remove(this);
					}
					this._calificacion.Entity = value;
					if ((value != null))
					{
						value.cita_medica.Add(this);
						this._id_calificacion = value.id_calificacion;
					}
					else
					{
						this._id_calificacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("calificacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_cita_medica", Storage="_centro_medico", ThisKey="id_centro_medico", OtherKey="id_centro_medico", IsForeignKey=true)]
		public centro_medico centro_medico
		{
			get
			{
				return this._centro_medico.Entity;
			}
			set
			{
				centro_medico previousValue = this._centro_medico.Entity;
				if (((previousValue != value) 
							|| (this._centro_medico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._centro_medico.Entity = null;
						previousValue.cita_medica.Remove(this);
					}
					this._centro_medico.Entity = value;
					if ((value != null))
					{
						value.cita_medica.Add(this);
						this._id_centro_medico = value.id_centro_medico;
					}
					else
					{
						this._id_centro_medico = default(int);
					}
					this.SendPropertyChanged("centro_medico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_cita_medica", Storage="_usuario", ThisKey="usuario_cedula", OtherKey="numero_cedula", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.cita_medica.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.cita_medica.Add(this);
						this._usuario_cedula = value.numero_cedula;
					}
					else
					{
						this._usuario_cedula = default(long);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.consulta")]
	public partial class consulta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_consulta;
		
		private System.DateTime _fecha;
		
		private long _usuario_numero_cedula;
		
		private int _centro_medico_id;
		
		private EntityRef<centro_medico> _centro_medico;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_consultaChanging(int value);
    partial void Onid_consultaChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onusuario_numero_cedulaChanging(long value);
    partial void Onusuario_numero_cedulaChanged();
    partial void Oncentro_medico_idChanging(int value);
    partial void Oncentro_medico_idChanged();
    #endregion
		
		public consulta()
		{
			this._centro_medico = default(EntityRef<centro_medico>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_consulta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_consulta
		{
			get
			{
				return this._id_consulta;
			}
			set
			{
				if ((this._id_consulta != value))
				{
					this.Onid_consultaChanging(value);
					this.SendPropertyChanging();
					this._id_consulta = value;
					this.SendPropertyChanged("id_consulta");
					this.Onid_consultaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_numero_cedula", DbType="BigInt NOT NULL")]
		public long usuario_numero_cedula
		{
			get
			{
				return this._usuario_numero_cedula;
			}
			set
			{
				if ((this._usuario_numero_cedula != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_numero_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usuario_numero_cedula = value;
					this.SendPropertyChanged("usuario_numero_cedula");
					this.Onusuario_numero_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_centro_medico_id", DbType="Int NOT NULL")]
		public int centro_medico_id
		{
			get
			{
				return this._centro_medico_id;
			}
			set
			{
				if ((this._centro_medico_id != value))
				{
					if (this._centro_medico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncentro_medico_idChanging(value);
					this.SendPropertyChanging();
					this._centro_medico_id = value;
					this.SendPropertyChanged("centro_medico_id");
					this.Oncentro_medico_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_consulta", Storage="_centro_medico", ThisKey="centro_medico_id", OtherKey="id_centro_medico", IsForeignKey=true)]
		public centro_medico centro_medico
		{
			get
			{
				return this._centro_medico.Entity;
			}
			set
			{
				centro_medico previousValue = this._centro_medico.Entity;
				if (((previousValue != value) 
							|| (this._centro_medico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._centro_medico.Entity = null;
						previousValue.consulta.Remove(this);
					}
					this._centro_medico.Entity = value;
					if ((value != null))
					{
						value.consulta.Add(this);
						this._centro_medico_id = value.id_centro_medico;
					}
					else
					{
						this._centro_medico_id = default(int);
					}
					this.SendPropertyChanged("centro_medico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_consulta", Storage="_usuario", ThisKey="usuario_numero_cedula", OtherKey="numero_cedula", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.consulta.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.consulta.Add(this);
						this._usuario_numero_cedula = value.numero_cedula;
					}
					else
					{
						this._usuario_numero_cedula = default(long);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eps")]
	public partial class eps : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nit;
		
		private string _nombre_eps;
		
		private int _numero_telefono;
		
		private string _direccion;
		
		private EntitySet<eps_has_centromedico> _eps_has_centromedico;
		
		private EntitySet<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnitChanging(string value);
    partial void OnnitChanged();
    partial void Onnombre_epsChanging(string value);
    partial void Onnombre_epsChanged();
    partial void Onnumero_telefonoChanging(int value);
    partial void Onnumero_telefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public eps()
		{
			this._eps_has_centromedico = new EntitySet<eps_has_centromedico>(new Action<eps_has_centromedico>(this.attach_eps_has_centromedico), new Action<eps_has_centromedico>(this.detach_eps_has_centromedico));
			this._usuario = new EntitySet<usuario>(new Action<usuario>(this.attach_usuario), new Action<usuario>(this.detach_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_eps", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_eps
		{
			get
			{
				return this._nombre_eps;
			}
			set
			{
				if ((this._nombre_eps != value))
				{
					this.Onnombre_epsChanging(value);
					this.SendPropertyChanging();
					this._nombre_eps = value;
					this.SendPropertyChanged("nombre_eps");
					this.Onnombre_epsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_telefono", DbType="Int NOT NULL")]
		public int numero_telefono
		{
			get
			{
				return this._numero_telefono;
			}
			set
			{
				if ((this._numero_telefono != value))
				{
					this.Onnumero_telefonoChanging(value);
					this.SendPropertyChanging();
					this._numero_telefono = value;
					this.SendPropertyChanged("numero_telefono");
					this.Onnumero_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eps_eps_has_centromedico", Storage="_eps_has_centromedico", ThisKey="nit", OtherKey="nit_eps")]
		public EntitySet<eps_has_centromedico> eps_has_centromedico
		{
			get
			{
				return this._eps_has_centromedico;
			}
			set
			{
				this._eps_has_centromedico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eps_usuario", Storage="_usuario", ThisKey="nit", OtherKey="nit_eps")]
		public EntitySet<usuario> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				this._usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_eps_has_centromedico(eps_has_centromedico entity)
		{
			this.SendPropertyChanging();
			entity.eps = this;
		}
		
		private void detach_eps_has_centromedico(eps_has_centromedico entity)
		{
			this.SendPropertyChanging();
			entity.eps = null;
		}
		
		private void attach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.eps = this;
		}
		
		private void detach_usuario(usuario entity)
		{
			this.SendPropertyChanging();
			entity.eps = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eps_has_centromedico")]
	public partial class eps_has_centromedico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nit_eps;
		
		private int _id_centro_medico;
		
		private EntityRef<centro_medico> _centro_medico;
		
		private EntityRef<eps> _eps;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnit_epsChanging(string value);
    partial void Onnit_epsChanged();
    partial void Onid_centro_medicoChanging(int value);
    partial void Onid_centro_medicoChanged();
    #endregion
		
		public eps_has_centromedico()
		{
			this._centro_medico = default(EntityRef<centro_medico>);
			this._eps = default(EntityRef<eps>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_eps", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nit_eps
		{
			get
			{
				return this._nit_eps;
			}
			set
			{
				if ((this._nit_eps != value))
				{
					if (this._eps.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnit_epsChanging(value);
					this.SendPropertyChanging();
					this._nit_eps = value;
					this.SendPropertyChanged("nit_eps");
					this.Onnit_epsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_centro_medico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_centro_medico
		{
			get
			{
				return this._id_centro_medico;
			}
			set
			{
				if ((this._id_centro_medico != value))
				{
					if (this._centro_medico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._id_centro_medico = value;
					this.SendPropertyChanged("id_centro_medico");
					this.Onid_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_eps_has_centromedico", Storage="_centro_medico", ThisKey="id_centro_medico", OtherKey="id_centro_medico", IsForeignKey=true)]
		public centro_medico centro_medico
		{
			get
			{
				return this._centro_medico.Entity;
			}
			set
			{
				centro_medico previousValue = this._centro_medico.Entity;
				if (((previousValue != value) 
							|| (this._centro_medico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._centro_medico.Entity = null;
						previousValue.eps_has_centromedico.Remove(this);
					}
					this._centro_medico.Entity = value;
					if ((value != null))
					{
						value.eps_has_centromedico.Add(this);
						this._id_centro_medico = value.id_centro_medico;
					}
					else
					{
						this._id_centro_medico = default(int);
					}
					this.SendPropertyChanged("centro_medico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eps_eps_has_centromedico", Storage="_eps", ThisKey="nit_eps", OtherKey="nit", IsForeignKey=true)]
		public eps eps
		{
			get
			{
				return this._eps.Entity;
			}
			set
			{
				eps previousValue = this._eps.Entity;
				if (((previousValue != value) 
							|| (this._eps.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eps.Entity = null;
						previousValue.eps_has_centromedico.Remove(this);
					}
					this._eps.Entity = value;
					if ((value != null))
					{
						value.eps_has_centromedico.Add(this);
						this._nit_eps = value.nit;
					}
					else
					{
						this._nit_eps = default(string);
					}
					this.SendPropertyChanged("eps");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.especialidad")]
	public partial class especialidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_especialidad;
		
		private string _nombre_especialidad;
		
		private EntitySet<centromedico_has_especialidad> _centromedico_has_especialidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_especialidadChanging(int value);
    partial void Onid_especialidadChanged();
    partial void Onnombre_especialidadChanging(string value);
    partial void Onnombre_especialidadChanged();
    #endregion
		
		public especialidad()
		{
			this._centromedico_has_especialidad = new EntitySet<centromedico_has_especialidad>(new Action<centromedico_has_especialidad>(this.attach_centromedico_has_especialidad), new Action<centromedico_has_especialidad>(this.detach_centromedico_has_especialidad));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialidad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_especialidad
		{
			get
			{
				return this._id_especialidad;
			}
			set
			{
				if ((this._id_especialidad != value))
				{
					this.Onid_especialidadChanging(value);
					this.SendPropertyChanging();
					this._id_especialidad = value;
					this.SendPropertyChanged("id_especialidad");
					this.Onid_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_especialidad", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_especialidad
		{
			get
			{
				return this._nombre_especialidad;
			}
			set
			{
				if ((this._nombre_especialidad != value))
				{
					this.Onnombre_especialidadChanging(value);
					this.SendPropertyChanging();
					this._nombre_especialidad = value;
					this.SendPropertyChanged("nombre_especialidad");
					this.Onnombre_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialidad_centromedico_has_especialidad", Storage="_centromedico_has_especialidad", ThisKey="id_especialidad", OtherKey="id_especialidad")]
		public EntitySet<centromedico_has_especialidad> centromedico_has_especialidad
		{
			get
			{
				return this._centromedico_has_especialidad;
			}
			set
			{
				this._centromedico_has_especialidad.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_centromedico_has_especialidad(centromedico_has_especialidad entity)
		{
			this.SendPropertyChanging();
			entity.especialidad = this;
		}
		
		private void detach_centromedico_has_especialidad(centromedico_has_especialidad entity)
		{
			this.SendPropertyChanging();
			entity.especialidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.telefono")]
	public partial class telefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_telefono;
		
		private int _numero_telefono;
		
		private int _id_centro_medico;
		
		private EntityRef<centro_medico> _centro_medico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_telefonoChanging(int value);
    partial void Onid_telefonoChanged();
    partial void Onnumero_telefonoChanging(int value);
    partial void Onnumero_telefonoChanged();
    partial void Onid_centro_medicoChanging(int value);
    partial void Onid_centro_medicoChanged();
    #endregion
		
		public telefono()
		{
			this._centro_medico = default(EntityRef<centro_medico>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_telefono", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_telefono
		{
			get
			{
				return this._id_telefono;
			}
			set
			{
				if ((this._id_telefono != value))
				{
					this.Onid_telefonoChanging(value);
					this.SendPropertyChanging();
					this._id_telefono = value;
					this.SendPropertyChanged("id_telefono");
					this.Onid_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_telefono", DbType="Int NOT NULL")]
		public int numero_telefono
		{
			get
			{
				return this._numero_telefono;
			}
			set
			{
				if ((this._numero_telefono != value))
				{
					this.Onnumero_telefonoChanging(value);
					this.SendPropertyChanging();
					this._numero_telefono = value;
					this.SendPropertyChanged("numero_telefono");
					this.Onnumero_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_centro_medico", DbType="Int NOT NULL")]
		public int id_centro_medico
		{
			get
			{
				return this._id_centro_medico;
			}
			set
			{
				if ((this._id_centro_medico != value))
				{
					if (this._centro_medico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_centro_medicoChanging(value);
					this.SendPropertyChanging();
					this._id_centro_medico = value;
					this.SendPropertyChanged("id_centro_medico");
					this.Onid_centro_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="centro_medico_telefono", Storage="_centro_medico", ThisKey="id_centro_medico", OtherKey="id_centro_medico", IsForeignKey=true)]
		public centro_medico centro_medico
		{
			get
			{
				return this._centro_medico.Entity;
			}
			set
			{
				centro_medico previousValue = this._centro_medico.Entity;
				if (((previousValue != value) 
							|| (this._centro_medico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._centro_medico.Entity = null;
						previousValue.telefono.Remove(this);
					}
					this._centro_medico.Entity = value;
					if ((value != null))
					{
						value.telefono.Add(this);
						this._id_centro_medico = value.id_centro_medico;
					}
					else
					{
						this._id_centro_medico = default(int);
					}
					this.SendPropertyChanged("centro_medico");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _numero_cedula;
		
		private string _nombres;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _nombre_usuario;
		
		private string _contrasena;
		
		private string _rol;
		
		private string _nit_eps;
		
		private EntitySet<cita_medica> _cita_medica;
		
		private EntitySet<consulta> _consulta;
		
		private EntityRef<eps> _eps;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnumero_cedulaChanging(long value);
    partial void Onnumero_cedulaChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void Onprimer_apellidoChanging(string value);
    partial void Onprimer_apellidoChanged();
    partial void Onsegundo_apellidoChanging(string value);
    partial void Onsegundo_apellidoChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    partial void Onnit_epsChanging(string value);
    partial void Onnit_epsChanged();
    #endregion
		
		public usuario()
		{
			this._cita_medica = new EntitySet<cita_medica>(new Action<cita_medica>(this.attach_cita_medica), new Action<cita_medica>(this.detach_cita_medica));
			this._consulta = new EntitySet<consulta>(new Action<consulta>(this.attach_consulta), new Action<consulta>(this.detach_consulta));
			this._eps = default(EntityRef<eps>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_cedula", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long numero_cedula
		{
			get
			{
				return this._numero_cedula;
			}
			set
			{
				if ((this._numero_cedula != value))
				{
					this.Onnumero_cedulaChanging(value);
					this.SendPropertyChanging();
					this._numero_cedula = value;
					this.SendPropertyChanged("numero_cedula");
					this.Onnumero_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this.Onprimer_apellidoChanging(value);
					this.SendPropertyChanging();
					this._primer_apellido = value;
					this.SendPropertyChanged("primer_apellido");
					this.Onprimer_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(MAX)")]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this.Onsegundo_apellidoChanging(value);
					this.SendPropertyChanging();
					this._segundo_apellido = value;
					this.SendPropertyChanged("segundo_apellido");
					this.Onsegundo_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_eps", DbType="VarChar(50)")]
		public string nit_eps
		{
			get
			{
				return this._nit_eps;
			}
			set
			{
				if ((this._nit_eps != value))
				{
					if (this._eps.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnit_epsChanging(value);
					this.SendPropertyChanging();
					this._nit_eps = value;
					this.SendPropertyChanged("nit_eps");
					this.Onnit_epsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_cita_medica", Storage="_cita_medica", ThisKey="numero_cedula", OtherKey="usuario_cedula")]
		public EntitySet<cita_medica> cita_medica
		{
			get
			{
				return this._cita_medica;
			}
			set
			{
				this._cita_medica.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_consulta", Storage="_consulta", ThisKey="numero_cedula", OtherKey="usuario_numero_cedula")]
		public EntitySet<consulta> consulta
		{
			get
			{
				return this._consulta;
			}
			set
			{
				this._consulta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="eps_usuario", Storage="_eps", ThisKey="nit_eps", OtherKey="nit", IsForeignKey=true)]
		public eps eps
		{
			get
			{
				return this._eps.Entity;
			}
			set
			{
				eps previousValue = this._eps.Entity;
				if (((previousValue != value) 
							|| (this._eps.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._eps.Entity = null;
						previousValue.usuario.Remove(this);
					}
					this._eps.Entity = value;
					if ((value != null))
					{
						value.usuario.Add(this);
						this._nit_eps = value.nit;
					}
					else
					{
						this._nit_eps = default(string);
					}
					this.SendPropertyChanged("eps");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_cita_medica(cita_medica entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_consulta(consulta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_consulta(consulta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	public partial class sp_consultar_cuantos_usuarios_consultaResult
	{
		
		private System.Nullable<int> _numes;
		
		private string _mes;
		
		private System.Nullable<int> _cantidad;
		
		public sp_consultar_cuantos_usuarios_consultaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numes", DbType="Int")]
		public System.Nullable<int> numes
		{
			get
			{
				return this._numes;
			}
			set
			{
				if ((this._numes != value))
				{
					this._numes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="NVarChar(30)")]
		public string mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this._mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
	}
	
	public partial class sp_loginResult
	{
		
		private long _numero_cedula;
		
		private string _nombres;
		
		private string _primer_apellido;
		
		private string _segundo_apellido;
		
		private string _nombre_usuario;
		
		private string _contrasena;
		
		private string _rol;
		
		private string _nit_eps;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_cedula", DbType="BigInt NOT NULL")]
		public long numero_cedula
		{
			get
			{
				return this._numero_cedula;
			}
			set
			{
				if ((this._numero_cedula != value))
				{
					this._numero_cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primer_apellido", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string primer_apellido
		{
			get
			{
				return this._primer_apellido;
			}
			set
			{
				if ((this._primer_apellido != value))
				{
					this._primer_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segundo_apellido", DbType="VarChar(MAX)")]
		public string segundo_apellido
		{
			get
			{
				return this._segundo_apellido;
			}
			set
			{
				if ((this._segundo_apellido != value))
				{
					this._segundo_apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this._nombre_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this._contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					this._rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit_eps", DbType="VarChar(50)")]
		public string nit_eps
		{
			get
			{
				return this._nit_eps;
			}
			set
			{
				if ((this._nit_eps != value))
				{
					this._nit_eps = value;
				}
			}
		}
	}
	
	public partial class sp_grafico_tortaResult
	{
		
		private long _usuario_numero_cedula;
		
		private System.Nullable<int> _conteo;
		
		public sp_grafico_tortaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_numero_cedula", DbType="BigInt NOT NULL")]
		public long usuario_numero_cedula
		{
			get
			{
				return this._usuario_numero_cedula;
			}
			set
			{
				if ((this._usuario_numero_cedula != value))
				{
					this._usuario_numero_cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conteo", DbType="Int")]
		public System.Nullable<int> conteo
		{
			get
			{
				return this._conteo;
			}
			set
			{
				if ((this._conteo != value))
				{
					this._conteo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
