<?xml version="1.0" encoding="utf-8"?><Database Name="hospitales" Class="OrmHospitalesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TJKQ4CV\SQLEXPRESS;Initial Catalog=hospitales;Integrated Security=True" SettingsObjectName="Logica.Properties.Settings" SettingsPropertyName="hospitalesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.calificacion" Member="calificacion">
    <Type Name="calificacion">
      <Column Name="id_calificacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="calificacion" Member="calificacion1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="calificacion_cita_medica" Member="cita_medica" ThisKey="id_calificacion" OtherKey="id_calificacion" Type="cita_medica" />
    </Type>
  </Table>
  <Table Name="dbo.centro_medico" Member="centro_medico">
    <Type Name="centro_medico">
      <Column Name="id_centro_medico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_centro_medico" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="nivel_atencion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="horarios" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="foto" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="centro_medico_centromedico_has_especialidad" Member="centromedico_has_especialidad" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="centromedico_has_especialidad" />
      <Association Name="centro_medico_cita_medica" Member="cita_medica" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="cita_medica" />
      <Association Name="centro_medico_consulta" Member="consulta" ThisKey="id_centro_medico" OtherKey="centro_medico_id" Type="consulta" />
      <Association Name="centro_medico_eps_has_centromedico" Member="eps_has_centromedico" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="eps_has_centromedico" />
      <Association Name="centro_medico_telefono" Member="telefono" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="telefono" />
    </Type>
  </Table>
  <Table Name="dbo.centromedico_has_especialidad" Member="centromedico_has_especialidad">
    <Type Name="centromedico_has_especialidad">
      <Column Name="id_centro_medico" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_especialidad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="centro_medico_centromedico_has_especialidad" Member="centro_medico" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="centro_medico" IsForeignKey="true" />
      <Association Name="especialidad_centromedico_has_especialidad" Member="especialidad" ThisKey="id_especialidad" OtherKey="id_especialidad" Type="especialidad" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cita_medica" Member="cita_medica">
    <Type Name="cita_medica">
      <Column Name="id_cita_medica" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha_hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_centro_medico" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usuario_cedula" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="id_calificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="calificacion_cita_medica" Member="calificacion" ThisKey="id_calificacion" OtherKey="id_calificacion" Type="calificacion" IsForeignKey="true" />
      <Association Name="centro_medico_cita_medica" Member="centro_medico" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="centro_medico" IsForeignKey="true" />
      <Association Name="usuario_cita_medica" Member="usuario" ThisKey="usuario_cedula" OtherKey="numero_cedula" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.consulta" Member="consulta">
    <Type Name="consulta">
      <Column Name="id_consulta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usuario_numero_cedula" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="centro_medico_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="centro_medico_consulta" Member="centro_medico" ThisKey="centro_medico_id" OtherKey="id_centro_medico" Type="centro_medico" IsForeignKey="true" />
      <Association Name="usuario_consulta" Member="usuario" ThisKey="usuario_numero_cedula" OtherKey="numero_cedula" Type="usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.eps" Member="eps">
    <Type Name="eps">
      <Column Name="nit" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_eps" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="numero_telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="eps_eps_has_centromedico" Member="eps_has_centromedico" ThisKey="nit" OtherKey="nit_eps" Type="eps_has_centromedico" />
      <Association Name="eps_usuario" Member="usuario" ThisKey="nit" OtherKey="nit_eps" Type="usuario" />
    </Type>
  </Table>
  <Table Name="dbo.eps_has_centromedico" Member="eps_has_centromedico">
    <Type Name="eps_has_centromedico">
      <Column Name="nit_eps" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_centro_medico" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="centro_medico_eps_has_centromedico" Member="centro_medico" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="centro_medico" IsForeignKey="true" />
      <Association Name="eps_eps_has_centromedico" Member="eps" ThisKey="nit_eps" OtherKey="nit" Type="eps" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.especialidad" Member="especialidad">
    <Type Name="especialidad">
      <Column Name="id_especialidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_especialidad" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="especialidad_centromedico_has_especialidad" Member="centromedico_has_especialidad" ThisKey="id_especialidad" OtherKey="id_especialidad" Type="centromedico_has_especialidad" />
    </Type>
  </Table>
  <Table Name="dbo.telefono" Member="telefono">
    <Type Name="telefono">
      <Column Name="id_telefono" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero_telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_centro_medico" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="centro_medico_telefono" Member="centro_medico" ThisKey="id_centro_medico" OtherKey="id_centro_medico" Type="centro_medico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.usuario" Member="usuario">
    <Type Name="usuario">
      <Column Name="numero_cedula" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="primer_apellido" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="segundo_apellido" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="nombre_usuario" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nit_eps" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="usuario_cita_medica" Member="cita_medica" ThisKey="numero_cedula" OtherKey="usuario_cedula" Type="cita_medica" />
      <Association Name="usuario_consulta" Member="consulta" ThisKey="numero_cedula" OtherKey="usuario_numero_cedula" Type="consulta" />
      <Association Name="eps_usuario" Member="eps" ThisKey="nit_eps" OtherKey="nit" Type="eps" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_consultar_cuantos_usuarios_consulta" Method="sp_consultar_cuantos_usuarios_consulta">
    <Parameter Name="fechaInicial" Type="System.DateTime" DbType="Date" />
    <Parameter Name="fechaFinal" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_consultar_cuantos_usuarios_consultaResult">
      <Column Name="numes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mes" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_login" Method="sp_login">
    <Parameter Name="nombre_usuario" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_loginResult">
      <Column Name="numero_cedula" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="primer_apellido" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="segundo_apellido" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="nombre_usuario" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nit_eps" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_grafico_torta" Method="sp_grafico_torta">
    <Parameter Name="centro_medico" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_grafico_tortaResult">
      <Column Name="usuario_numero_cedula" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="conteo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>